# Generated by Django 4.2.6 on 2023-10-13 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_orderdetail"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderdetail",
            old_name="strip_payment_intent",
            new_name="stripe_payment_intent",
        ),
    ]
